---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: ${BACKEND_REPO}
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    properties:
      - name: APP_ENV
        value: template
        type: text
      - name: CF_APP_NAME
        value: undefined
        type: text
    jobs:
      - name: Deploy to dev
        type: deployer
        script: |-
          #!/bin/bash
          sed -i  "s/myenv/${APP_ENV}/g" manifest.yml
          cf create-service cloudantNoSQLDB Lite iot4i-starter-cloudantNoSQLDB
          cf push "${CF_APP_NAME}" --no-start
          cf bind-service "${CF_APP_NAME}" iot4i-starter-cloudantNoSQLDB
          cf start "${CF_APP_NAME}"
        target:
          organization: ${STAGING_REGION_ID}
          space: ${STAGING_ORG_NAME}
          url: ${STAGING_SPACE_NAME}
          application: ${CF_APP_NAME}
