---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: ${BACKEND_REPO}
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    properties:
      - name: APP_ENV
        value: template
        type: text
    jobs:
      - name: Deploy to dev
        type: deployer
        script: |-
          #!/bin/bash
          #Remove the 'export' and 'sed' lines from the configuration of 
          #the Deploy Stage when you have set APP_ENV in the manifest.yml and created a 
          #corresponding config/config-$env.json file
          sed -i  "s/myenv/${APP_ENV}/g" manifest.yml
          cf create-service cloudantNoSQLDB Lite iot4i-starter-cloudantNoSQLDB
          cf push "${CF_APP}" --no-start
          cf bind-service "${CF_APP}" iot4i-starter-cloudantNoSQLDB
          cf start "${CF_APP}"
        target:
          organization: ${STAGING_REGION_ID}
          space: ${STAGING_ORG_NAME}
          url: ${STAGING_SPACE_NAME}
          application: ${CF_APP_NAME}
