---
stages:
- name: Build Stage
  inputs:
  - url: https://git.ng.bluemix.net/maeve.oreilly/ioti-policy-holder-app2.git
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: tenant
    value: '123456'
    type: text
  jobs:
  - name: Deploy
    type: deployer
    deploy_permission: DEV_IN_SPACE
    target:
      region_id: ibm:yp:us-south
      organization: maeve.oreilly@ie.ibm.com
      space: dev
      application: Deliver Policy Holder App
    script: |
      #!/bin/bash
      export APP_ENV=template
      cf create-service cloudantNoSQLDB Lite iot4i-starter-cloudantNoSQLDB
      sed -i  "s/myenv/$APP_ENV/g" manifest.yml
      cf push "${CF_APP}" --no-start
      cf bind-service "${CF_APP}" iot4i-starter-cloudantNoSQLDB
      cf start "${CF_APP}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
