---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: ${POLICY_HOLDER_REPO}
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    properties:
      - name: APP_ENV
        value: template
        type: text
      - name: CF_APP_NAME
        value: undefined
        type: text
    jobs:
      - name: Deploy
        type: deployer
        script: |-
          #!/bin/bash
          cf push "${CF_APP}" --no-start
          cf start "${CF_APP}"
        target:
          region_id: ${STAGING_REGION_ID}
          organization: ${STAGING_ORG_NAME}
          space: ${STAGING_SPACE_NAME}
          application: ${CF_APP_NAME}

